{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "47bc5b63",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-14 08:59:43.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.442 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.451 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.467 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.469 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.474 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.477 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-14 08:59:43.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Database created successfully!\n"
     ]
    }
   ],
   "source": [
    "# Import required libraries\n",
    "import pandas as pd\n",
    "import sqlite3\n",
    "from datetime import datetime\n",
    "from abc import ABC, abstractmethod\n",
    "import streamlit as st\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from typing import List, Dict, Optional\n",
    "import hashlib\n",
    "import re\n",
    "\n",
    "# ============================================\n",
    "# DATABASE SETUP\n",
    "# ============================================\n",
    "\n",
    "def create_database():\n",
    "    \"\"\"Create SQLite database and tables\"\"\"\n",
    "    conn = sqlite3.connect('tax_arrears.db')\n",
    "    cursor = conn.cursor()\n",
    "    \n",
    "    # Create Taxpayers table\n",
    "    cursor.execute('''\n",
    "        CREATE TABLE IF NOT EXISTS taxpayers (\n",
    "            pin_no TEXT PRIMARY KEY,\n",
    "            tax_payer_name TEXT NOT NULL,\n",
    "            phone_no TEXT,\n",
    "            station_name TEXT,\n",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n",
    "        )\n",
    "    ''')\n",
    "    \n",
    "    # Create Tax Records table (renamed from tax_obligations)\n",
    "    cursor.execute('''\n",
    "        CREATE TABLE IF NOT EXISTS tax_records (\n",
    "            record_id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            pin_no TEXT,\n",
    "            obligation_name TEXT NOT NULL,\n",
    "            from_date DATE,\n",
    "            to_date DATE,\n",
    "            principal REAL DEFAULT 0,\n",
    "            penalty REAL DEFAULT 0,\n",
    "            interest REAL DEFAULT 0,\n",
    "            grand_total REAL DEFAULT 0,\n",
    "            status TEXT DEFAULT 'PENDING',\n",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n",
    "            FOREIGN KEY (pin_no) REFERENCES taxpayers(pin_no)\n",
    "        )\n",
    "    ''')\n",
    "    \n",
    "    # Create Audit Log table\n",
    "    cursor.execute('''\n",
    "        CREATE TABLE IF NOT EXISTS audit_log (\n",
    "            log_id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            action TEXT,\n",
    "            pin_no TEXT,\n",
    "            record_id INTEGER,\n",
    "            old_value TEXT,\n",
    "            new_value TEXT,\n",
    "            changed_by TEXT DEFAULT 'SYSTEM',\n",
    "            changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n",
    "        )\n",
    "    ''')\n",
    "    \n",
    "    # Create Users table for authentication\n",
    "    cursor.execute('''\n",
    "        CREATE TABLE IF NOT EXISTS users (\n",
    "            user_id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            username TEXT UNIQUE NOT NULL,\n",
    "            password_hash TEXT NOT NULL,\n",
    "            role TEXT DEFAULT 'VIEWER',\n",
    "            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n",
    "        )\n",
    "    ''')\n",
    "    \n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "    print(\"Database created successfully!\")\n",
    "\n",
    "# ============================================\n",
    "# OOP CLASSES\n",
    "# ============================================\n",
    "\n",
    "class Taxpayer:\n",
    "    \"\"\"Represents a taxpayer entity\"\"\"\n",
    "    \n",
    "    def __init__(self, pin_no: str, tax_payer_name: str, phone_no: str = None, station_name: str = None):\n",
    "        self._pin_no = pin_no\n",
    "        self._tax_payer_name = tax_payer_name\n",
    "        self._phone_no = self._clean_phone(phone_no) if phone_no else None\n",
    "        self._station_name = station_name\n",
    "        self._records = []  # Renamed from _obligations\n",
    "    \n",
    "    def _clean_phone(self, phone: str) -> str:\n",
    "        \"\"\"Clean phone number by removing spaces and special characters\"\"\"\n",
    "        if phone:\n",
    "            return re.sub(r'[^\\d+]', '', str(phone))\n",
    "        return None\n",
    "    \n",
    "    # Properties with getters\n",
    "    @property\n",
    "    def pin_no(self):\n",
    "        return self._pin_no\n",
    "    \n",
    "    @property\n",
    "    def tax_payer_name(self):\n",
    "        return self._tax_payer_name\n",
    "    \n",
    "    @property\n",
    "    def phone_no(self):\n",
    "        return self._phone_no\n",
    "    \n",
    "    @property\n",
    "    def station_name(self):\n",
    "        return self._station_name\n",
    "    \n",
    "    def add_record(self, record):  # Renamed from add_obligation\n",
    "        \"\"\"Add a tax record to this taxpayer\"\"\"\n",
    "        self._records.append(record)\n",
    "    \n",
    "    def get_total_arrears(self) -> float:\n",
    "        \"\"\"Calculate total arrears for this taxpayer\"\"\"\n",
    "        return sum(record.grand_total for record in self._records)\n",
    "    \n",
    "    def get_outstanding_balance(self) -> float:\n",
    "        \"\"\"Calculate outstanding balance\"\"\"\n",
    "        total_principal = sum(record.principal for record in self._records)\n",
    "        return total_principal\n",
    "    \n",
    "    def to_dict(self) -> Dict:\n",
    "        \"\"\"Convert taxpayer object to dictionary\"\"\"\n",
    "        return {\n",
    "            'pin_no': self._pin_no,\n",
    "            'tax_payer_name': self._tax_payer_name,\n",
    "            'phone_no': self._phone_no,\n",
    "            'station_name': self._station_name\n",
    "        }\n",
    "\n",
    "\n",
    "class TaxRecord:  # Renamed from TaxObligation\n",
    "    \"\"\"Represents a tax record entity\"\"\"\n",
    "    \n",
    "    def __init__(self, pin_no: str, obligation_name: str, from_date: str = None,\n",
    "                 to_date: str = None, principal: float = 0, penalty: float = 0,\n",
    "                 interest: float = 0):\n",
    "        self._pin_no = pin_no\n",
    "        self._obligation_name = obligation_name\n",
    "        self._from_date = from_date\n",
    "        self._to_date = to_date\n",
    "        self._principal = self._clean_amount(principal)\n",
    "        self._penalty = self._clean_amount(penalty)\n",
    "        self._interest = self._clean_amount(interest)\n",
    "        self._grand_total = self._principal + self._penalty + self._interest\n",
    "        self._status = self._determine_status()\n",
    "    \n",
    "    def _clean_amount(self, amount) -> float:\n",
    "        \"\"\"Clean amount by removing commas and converting to float\"\"\"\n",
    "        if isinstance(amount, str):\n",
    "            amount = amount.replace(',', '').replace('\"', '').strip()\n",
    "            if amount in ['-', '']:\n",
    "                return 0.0\n",
    "        try:\n",
    "            return float(amount)\n",
    "        except (ValueError, TypeError):\n",
    "            return 0.0\n",
    "    \n",
    "    @property\n",
    "    def grand_total(self):\n",
    "        return self._grand_total\n",
    "    \n",
    "    @property\n",
    "    def principal(self):\n",
    "        return self._principal\n",
    "    \n",
    "    @property\n",
    "    def obligation_name(self):\n",
    "        return self._obligation_name\n",
    "    \n",
    "    def _determine_status(self) -> str:\n",
    "        \"\"\"Determine the status of the record\"\"\"\n",
    "        if self._grand_total <= 0:\n",
    "            return \"PAID\"\n",
    "        elif self._penalty > 0 or self._interest > 0:\n",
    "            return \"PENALTY_APPLIED\"\n",
    "        else:\n",
    "            return \"PENDING\"\n",
    "    \n",
    "    def to_dict(self) -> Dict:\n",
    "        \"\"\"Convert record object to dictionary\"\"\"\n",
    "        return {\n",
    "            'pin_no': self._pin_no,\n",
    "            'obligation_name': self._obligation_name,\n",
    "            'from_date': self._from_date,\n",
    "            'to_date': self._to_date,\n",
    "            'principal': self._principal,\n",
    "            'penalty': self._penalty,\n",
    "            'interest': self._interest,\n",
    "            'grand_total': self._grand_total,\n",
    "            'status': self._status\n",
    "        }\n",
    "\n",
    "\n",
    "class DatabaseManager:\n",
    "    \"\"\"Handles all database operations\"\"\"\n",
    "    \n",
    "    def __init__(self, db_path='tax_arrears.db'):\n",
    "        self.db_path = db_path\n",
    "    \n",
    "    def get_connection(self):\n",
    "        \"\"\"Get database connection\"\"\"\n",
    "        return sqlite3.connect(self.db_path)\n",
    "    \n",
    "    def insert_taxpayer(self, taxpayer: Taxpayer) -> bool:\n",
    "        \"\"\"Insert a taxpayer into the database\"\"\"\n",
    "        try:\n",
    "            conn = self.get_connection()\n",
    "            cursor = conn.cursor()\n",
    "            cursor.execute('''\n",
    "                INSERT OR REPLACE INTO taxpayers \n",
    "                (pin_no, tax_payer_name, phone_no, station_name)\n",
    "                VALUES (?, ?, ?, ?)\n",
    "            ''', (taxpayer.pin_no, taxpayer.tax_payer_name, \n",
    "                  taxpayer.phone_no, taxpayer.station_name))\n",
    "            conn.commit()\n",
    "            conn.close()\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Error inserting taxpayer: {e}\")\n",
    "            return False\n",
    "    \n",
    "    def insert_tax_record(self, record: TaxRecord) -> bool:  # Renamed from insert_obligation\n",
    "        \"\"\"Insert a tax record into the database\"\"\"\n",
    "        try:\n",
    "            conn = self.get_connection()\n",
    "            cursor = conn.cursor()\n",
    "            cursor.execute('''\n",
    "                INSERT INTO tax_records \n",
    "                (pin_no, obligation_name, from_date, to_date, principal, \n",
    "                 penalty, interest, grand_total, status)\n",
    "                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)\n",
    "            ''', (record._pin_no, record._obligation_name, \n",
    "                  record._from_date, record._to_date,\n",
    "                  record._principal, record._penalty,\n",
    "                  record._interest, record._grand_total,\n",
    "                  record._status))\n",
    "            conn.commit()\n",
    "            conn.close()\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"Error inserting tax record: {e}\")\n",
    "            return False\n",
    "    \n",
    "    def get_taxpayer_records(self, pin_no: str) -> List[Dict]:  # Renamed from get_taxpayer_obligations\n",
    "        \"\"\"Get all records for a specific taxpayer\"\"\"\n",
    "        conn = self.get_connection()\n",
    "        query = '''\n",
    "            SELECT r.*, t.tax_payer_name, t.phone_no \n",
    "            FROM tax_records r\n",
    "            JOIN taxpayers t ON r.pin_no = t.pin_no\n",
    "            WHERE r.pin_no = ?\n",
    "            ORDER BY r.from_date DESC\n",
    "        '''\n",
    "        df = pd.read_sql_query(query, conn, params=(pin_no,))\n",
    "        conn.close()\n",
    "        return df.to_dict('records')\n",
    "    \n",
    "    def get_all_taxpayers(self) -> pd.DataFrame:\n",
    "        \"\"\"Get all taxpayers with their summary information\"\"\"\n",
    "        conn = self.get_connection()\n",
    "        query = '''\n",
    "            SELECT \n",
    "                t.pin_no,\n",
    "                t.tax_payer_name,\n",
    "                t.phone_no,\n",
    "                t.station_name,\n",
    "                COUNT(r.record_id) as total_records,\n",
    "                SUM(r.principal) as total_principal,\n",
    "                SUM(r.penalty) as total_penalty,\n",
    "                SUM(r.interest) as total_interest,\n",
    "                SUM(r.grand_total) as total_arrears,\n",
    "                SUM(CASE WHEN r.status = 'PENDING' THEN 1 ELSE 0 END) as pending_count,\n",
    "                SUM(CASE WHEN r.status = 'PENALTY_APPLIED' THEN 1 ELSE 0 END) as penalty_count\n",
    "            FROM taxpayers t\n",
    "            LEFT JOIN tax_records r ON t.pin_no = r.pin_no\n",
    "            GROUP BY t.pin_no\n",
    "        '''\n",
    "        df = pd.read_sql_query(query, conn)\n",
    "        conn.close()\n",
    "        return df\n",
    "    \n",
    "    def get_summary_statistics(self) -> Dict:\n",
    "        \"\"\"Get summary statistics for the dashboard\"\"\"\n",
    "        conn = self.get_connection()\n",
    "        \n",
    "        stats = {}\n",
    "        \n",
    "        # Total taxpayers\n",
    "        stats['total_taxpayers'] = pd.read_sql_query(\n",
    "            \"SELECT COUNT(*) as count FROM taxpayers\", conn\n",
    "        ).iloc[0]['count']\n",
    "        \n",
    "        # Total records\n",
    "        stats['total_records'] = pd.read_sql_query(\n",
    "            \"SELECT COUNT(*) as count FROM tax_records\", conn\n",
    "        ).iloc[0]['count']\n",
    "        \n",
    "        # Total arrears\n",
    "        total_arrears = pd.read_sql_query(\n",
    "            \"SELECT SUM(grand_total) as total FROM tax_records\", conn\n",
    "        ).iloc[0]['total']\n",
    "        stats['total_arrears'] = total_arrears if total_arrears else 0\n",
    "        \n",
    "        # Total penalties\n",
    "        total_penalties = pd.read_sql_query(\n",
    "            \"SELECT SUM(penalty) as total FROM tax_records\", conn\n",
    "        ).iloc[0]['total']\n",
    "        stats['total_penalties'] = total_penalties if total_penalties else 0\n",
    "        \n",
    "        # Total interest\n",
    "        total_interest = pd.read_sql_query(\n",
    "            \"SELECT SUM(interest) as total FROM tax_records\", conn\n",
    "        ).iloc[0]['total']\n",
    "        stats['total_interest'] = total_interest if total_interest else 0\n",
    "        \n",
    "        # By station\n",
    "        stats['by_station'] = pd.read_sql_query('''\n",
    "            SELECT station_name, COUNT(*) as count, SUM(r.grand_total) as arrears\n",
    "            FROM taxpayers t\n",
    "            JOIN tax_records r ON t.pin_no = r.pin_no\n",
    "            GROUP BY station_name\n",
    "        ''', conn)\n",
    "        \n",
    "        # By obligation type\n",
    "        stats['by_obligation'] = pd.read_sql_query('''\n",
    "            SELECT obligation_name, COUNT(*) as count, SUM(grand_total) as arrears\n",
    "            FROM tax_records\n",
    "            GROUP BY obligation_name\n",
    "        ''', conn)\n",
    "        \n",
    "        conn.close()\n",
    "        return stats\n",
    "\n",
    "\n",
    "class DataImporter:\n",
    "    \"\"\"Handles importing data from CSV\"\"\"\n",
    "    \n",
    "    @staticmethod\n",
    "    def clean_value(value):\n",
    "        \"\"\"Clean CSV values by removing quotes and commas\"\"\"\n",
    "        if pd.isna(value):\n",
    "            return None\n",
    "        value = str(value).strip()\n",
    "        value = value.replace('\"', '').replace(',', '')\n",
    "        if value == '-' or value == '':\n",
    "            return None\n",
    "        return value\n",
    "    \n",
    "    @staticmethod\n",
    "    def import_from_csv(file_path: str, db_manager: DatabaseManager) -> Dict:\n",
    "        \"\"\"Import data from CSV file to database\"\"\"\n",
    "        try:\n",
    "            # Read CSV file\n",
    "            df = pd.read_csv(file_path)\n",
    "            \n",
    "            stats = {'taxpayers_added': 0, 'records_added': 0, 'errors': 0}\n",
    "            processed_pins = set()\n",
    "            \n",
    "            # Process each row\n",
    "            for _, row in df.iterrows():\n",
    "                try:\n",
    "                    # Clean data\n",
    "                    pin_no = DataImporter.clean_value(row.get('pin', ''))\n",
    "                    if not pin_no:\n",
    "                        continue\n",
    "                    \n",
    "                    # Create or update taxpayer\n",
    "                    if pin_no not in processed_pins:\n",
    "                        taxpayer = Taxpayer(\n",
    "                            pin_no=pin_no,\n",
    "                            tax_payer_name=DataImporter.clean_value(row.get('tax_payer_name', '')),\n",
    "                            phone_no=DataImporter.clean_value(row.get('phone_no', '')),\n",
    "                            station_name=DataImporter.clean_value(row.get('station_name', ''))\n",
    "                        )\n",
    "                        \n",
    "                        if db_manager.insert_taxpayer(taxpayer):\n",
    "                            stats['taxpayers_added'] += 1\n",
    "                            processed_pins.add(pin_no)\n",
    "                    \n",
    "                    # Create tax record\n",
    "                    record = TaxRecord(\n",
    "                        pin_no=pin_no,\n",
    "                        obligation_name=DataImporter.clean_value(row.get('obligation_name', '')),\n",
    "                        from_date=DataImporter.clean_value(row.get('from_date', '')),\n",
    "                        to_date=DataImporter.clean_value(row.get('to_date', '')),\n",
    "                        principal=DataImporter.clean_value(row.get('PRINCIPAL', 0)),\n",
    "                        penalty=DataImporter.clean_value(row.get('PENALTY', 0)),\n",
    "                        interest=DataImporter.clean_value(row.get('INTEREST', 0))\n",
    "                    )\n",
    "                    \n",
    "                    if db_manager.insert_tax_record(record):\n",
    "                        stats['records_added'] += 1\n",
    "                        \n",
    "                except Exception as e:\n",
    "                    stats['errors'] += 1\n",
    "                    print(f\"Error processing row: {e}\")\n",
    "            \n",
    "            return stats\n",
    "            \n",
    "        except Exception as e:\n",
    "            return {'error': str(e)}\n",
    "\n",
    "\n",
    "# ============================================\n",
    "# STREAMLIT APPLICATION\n",
    "# ============================================\n",
    "\n",
    "def init_session_state():\n",
    "    \"\"\"Initialize session state variables\"\"\"\n",
    "    if 'authenticated' not in st.session_state:\n",
    "        st.session_state.authenticated = False\n",
    "    if 'username' not in st.session_state:\n",
    "        st.session_state.username = None\n",
    "    if 'role' not in st.session_state:\n",
    "        st.session_state.role = 'VIEWER'\n",
    "\n",
    "\n",
    "def login_page():\n",
    "    \"\"\"Login page for the application\"\"\"\n",
    "    st.title(\"🔐 Tax Arrears Management System - Login\")\n",
    "    \n",
    "    col1, col2, col3 = st.columns([1, 2, 1])\n",
    "    \n",
    "    with col2:\n",
    "        st.markdown(\"\"\"\n",
    "        <div style='text-align: center; padding: 20px;'>\n",
    "            <h2>Welcome to TAMS</h2>\n",
    "            <p>Please login to access the system</p>\n",
    "        </div>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "        \n",
    "        username = st.text_input(\"Username\")\n",
    "        password = st.text_input(\"Password\", type=\"password\")\n",
    "        \n",
    "        if st.button(\"Login\", use_container_width=True):\n",
    "            # Simple authentication (in production, use proper authentication)\n",
    "            if username == \"admin\" and password == \"admin123\":\n",
    "                st.session_state.authenticated = True\n",
    "                st.session_state.username = username\n",
    "                st.session_state.role = \"ADMIN\"\n",
    "                st.success(\"Login successful!\")\n",
    "                st.rerun()\n",
    "            elif username == \"viewer\" and password == \"viewer123\":\n",
    "                st.session_state.authenticated = True\n",
    "                st.session_state.username = username\n",
    "                st.session_state.role = \"VIEWER\"\n",
    "                st.success(\"Login successful!\")\n",
    "                st.rerun()\n",
    "            else:\n",
    "                st.error(\"Invalid username or password\")\n",
    "\n",
    "\n",
    "def dashboard_page(db_manager):\n",
    "    \"\"\"Main dashboard page\"\"\"\n",
    "    st.title(\"📊 Tax Arrears Dashboard\")\n",
    "    \n",
    "    # Get statistics\n",
    "    stats = db_manager.get_summary_statistics()\n",
    "    \n",
    "    # Display KPI cards\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    \n",
    "    with col1:\n",
    "        st.metric(\"Total Taxpayers\", f\"{stats['total_taxpayers']:,}\")\n",
    "    \n",
    "    with col2:\n",
    "        st.metric(\"Total Records\", f\"{stats['total_records']:,}\")  # Renamed from total_obligations\n",
    "    \n",
    "    with col3:\n",
    "        st.metric(\"Total Arrears\", f\"KES {stats['total_arrears']:,.0f}\")\n",
    "    \n",
    "    with col4:\n",
    "        st.metric(\"Total Penalties\", f\"KES {stats['total_penalties']:,.0f}\")\n",
    "    \n",
    "    # Charts\n",
    "    col1, col2 = st.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        st.subheader(\"Arrears by Station\")\n",
    "        if not stats['by_station'].empty:\n",
    "            fig = px.pie(stats['by_station'], values='arrears', names='station_name',\n",
    "                         title='Distribution of Tax Arrears by Station')\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "        else:\n",
    "            st.info(\"No data available for station-wise analysis\")\n",
    "    \n",
    "    with col2:\n",
    "        st.subheader(\"Records by Obligation Type\")  # Renamed\n",
    "        if not stats['by_obligation'].empty:\n",
    "            fig = px.bar(stats['by_obligation'].head(10), \n",
    "                         x='obligation_name', y='count',\n",
    "                         title='Top 10 Obligation Types',\n",
    "                         labels={'count': 'Number of Records',  # Renamed\n",
    "                                'obligation_name': 'Obligation Type'})\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "        else:\n",
    "            st.info(\"No data available for obligation type analysis\")\n",
    "    \n",
    "    # Recent taxpayers\n",
    "    st.subheader(\"Recent Taxpayers\")\n",
    "    df_taxpayers = db_manager.get_all_taxpayers()\n",
    "    if not df_taxpayers.empty:\n",
    "        st.dataframe(\n",
    "            df_taxpayers[['pin_no', 'tax_payer_name', 'station_name', \n",
    "                          'total_records', 'total_principal', 'total_arrears']].head(10),  # Renamed\n",
    "            use_container_width=True,\n",
    "            hide_index=True\n",
    "        )\n",
    "\n",
    "\n",
    "def taxpayers_page(db_manager):\n",
    "    \"\"\"Taxpayers management page\"\"\"\n",
    "    st.title(\"👥 Taxpayers Management\")\n",
    "    \n",
    "    # Get all taxpayers\n",
    "    df = db_manager.get_all_taxpayers()\n",
    "    \n",
    "    if df.empty:\n",
    "        st.info(\"No taxpayers found in the database\")\n",
    "        return\n",
    "    \n",
    "    # Search and filter\n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        search_term = st.text_input(\"🔍 Search by name or PIN\", \"\")\n",
    "    \n",
    "    with col2:\n",
    "        station_filter = st.multiselect(\"Filter by Station\", \n",
    "                                        options=df['station_name'].unique())\n",
    "    \n",
    "    # Apply filters\n",
    "    filtered_df = df.copy()\n",
    "    if search_term:\n",
    "        filtered_df = filtered_df[\n",
    "            filtered_df['tax_payer_name'].str.contains(search_term, case=False, na=False) |\n",
    "            filtered_df['pin_no'].str.contains(search_term, case=False, na=False)\n",
    "        ]\n",
    "    \n",
    "    if station_filter:\n",
    "        filtered_df = filtered_df[filtered_df['station_name'].isin(station_filter)]\n",
    "    \n",
    "    # Display\n",
    "    st.dataframe(\n",
    "        filtered_df[['pin_no', 'tax_payer_name', 'station_name', 'phone_no',\n",
    "                    'total_records', 'total_principal', 'total_penalty',\n",
    "                    'total_interest', 'total_arrears']],  # Renamed\n",
    "        use_container_width=True,\n",
    "        hide_index=True\n",
    "    )\n",
    "    \n",
    "    # Export option\n",
    "    if st.button(\"📥 Export to CSV\"):\n",
    "        csv = filtered_df.to_csv(index=False)\n",
    "        st.download_button(\n",
    "            label=\"Download CSV\",\n",
    "            data=csv,\n",
    "            file_name=f\"taxpayers_{datetime.now().strftime('%Y%m%d')}.csv\",\n",
    "            mime=\"text/csv\"\n",
    "        )\n",
    "\n",
    "\n",
    "def records_page(db_manager):  # Renamed from obligations_page\n",
    "    \"\"\"Tax records management page\"\"\"\n",
    "    st.title(\"📋 Tax Records\")\n",
    "    \n",
    "    conn = db_manager.get_connection()\n",
    "    \n",
    "    # Get all records with taxpayer details\n",
    "    query = '''\n",
    "        SELECT \n",
    "            r.record_id,\n",
    "            t.pin_no,\n",
    "            t.tax_payer_name,\n",
    "            r.obligation_name,\n",
    "            r.from_date,\n",
    "            r.to_date,\n",
    "            r.principal,\n",
    "            r.penalty,\n",
    "            r.interest,\n",
    "            r.grand_total,\n",
    "            r.status\n",
    "        FROM tax_records r\n",
    "        JOIN taxpayers t ON r.pin_no = t.pin_no\n",
    "        ORDER BY r.from_date DESC\n",
    "    '''\n",
    "    df = pd.read_sql_query(query, conn)\n",
    "    conn.close()\n",
    "    \n",
    "    if df.empty:\n",
    "        st.info(\"No tax records found in the database\")\n",
    "        return\n",
    "    \n",
    "    # Filters\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    \n",
    "    with col1:\n",
    "        status_filter = st.multiselect(\"Filter by Status\", \n",
    "                                      options=df['status'].unique())\n",
    "    \n",
    "    with col2:\n",
    "        name_filter = st.text_input(\"Search by taxpayer name\", \"\")\n",
    "    \n",
    "    with col3:\n",
    "        min_amount = st.number_input(\"Minimum amount\", min_value=0, value=0, step=1000)\n",
    "    \n",
    "    # Apply filters\n",
    "    filtered_df = df.copy()\n",
    "    if status_filter:\n",
    "        filtered_df = filtered_df[filtered_df['status'].isin(status_filter)]\n",
    "    \n",
    "    if name_filter:\n",
    "        filtered_df = filtered_df[filtered_df['tax_payer_name'].str.contains(name_filter, case=False, na=False)]\n",
    "    \n",
    "    if min_amount > 0:\n",
    "        filtered_df = filtered_df[filtered_df['grand_total'] >= min_amount]\n",
    "    \n",
    "    # Display\n",
    "    st.dataframe(\n",
    "        filtered_df,\n",
    "        use_container_width=True,\n",
    "        hide_index=True\n",
    "    )\n",
    "    \n",
    "    # Summary\n",
    "    st.subheader(\"Summary\")\n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    with col1:\n",
    "        st.metric(\"Total Records\", len(filtered_df))  # Renamed\n",
    "    with col2:\n",
    "        st.metric(\"Total Principal\", f\"KES {filtered_df['principal'].sum():,.0f}\")\n",
    "    with col3:\n",
    "        st.metric(\"Total Penalties\", f\"KES {filtered_df['penalty'].sum():,.0f}\")\n",
    "    with col4:\n",
    "        st.metric(\"Total Interest\", f\"KES {filtered_df['interest'].sum():,.0f}\")\n",
    "\n",
    "\n",
    "def analytics_page(db_manager):\n",
    "    \"\"\"Advanced analytics page\"\"\"\n",
    "    st.title(\"📈 Advanced Analytics\")\n",
    "    \n",
    "    conn = db_manager.get_connection()\n",
    "    \n",
    "    # Time series analysis\n",
    "    query = '''\n",
    "        SELECT \n",
    "            strftime('%Y', from_date) as year,\n",
    "            COUNT(*) as record_count,\n",
    "            SUM(principal) as total_principal,\n",
    "            SUM(penalty) as total_penalty,\n",
    "            SUM(interest) as total_interest,\n",
    "            SUM(grand_total) as total_arrears\n",
    "        FROM tax_records\n",
    "        WHERE from_date IS NOT NULL AND from_date != ''\n",
    "        GROUP BY year\n",
    "        ORDER BY year\n",
    "    '''\n",
    "    df_yearly = pd.read_sql_query(query, conn)\n",
    "    \n",
    "    if not df_yearly.empty:\n",
    "        col1, col2 = st.columns(2)\n",
    "        \n",
    "        with col1:\n",
    "            fig = px.line(df_yearly, x='year', y='total_principal',\n",
    "                          title='Annual Tax Principal Trend',\n",
    "                          labels={'total_principal': 'Total Principal (KES)', 'year': 'Year'})\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "        \n",
    "        with col2:\n",
    "            fig = px.bar(df_yearly, x='year', y='record_count',\n",
    "                         title='Annual Record Count',\n",
    "                         labels={'record_count': 'Number of Records', 'year': 'Year'})\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "    \n",
    "    # Top defaulters\n",
    "    query = '''\n",
    "        SELECT \n",
    "            t.tax_payer_name,\n",
    "            t.pin_no,\n",
    "            COUNT(r.record_id) as records,\n",
    "            SUM(r.grand_total) as total_arrears,\n",
    "            SUM(r.penalty) as total_penalties\n",
    "        FROM taxpayers t\n",
    "        JOIN tax_records r ON t.pin_no = r.pin_no\n",
    "        WHERE r.grand_total > 0\n",
    "        GROUP BY t.pin_no\n",
    "        ORDER BY total_arrears DESC\n",
    "        LIMIT 10\n",
    "    '''\n",
    "    df_top = pd.read_sql_query(query, conn)\n",
    "    \n",
    "    st.subheader(\"Top 10 Defaulters\")\n",
    "    if not df_top.empty:\n",
    "        fig = px.bar(df_top, x='tax_payer_name', y='total_arrears',\n",
    "                     title='Top 10 Taxpayers by Arrears Amount',\n",
    "                     labels={'total_arrears': 'Total Arrears (KES)', 'tax_payer_name': 'Taxpayer'})\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "    \n",
    "    # Status distribution\n",
    "    query = '''\n",
    "        SELECT \n",
    "            status,\n",
    "            COUNT(*) as count,\n",
    "            SUM(grand_total) as total_amount\n",
    "        FROM tax_records\n",
    "        GROUP BY status\n",
    "    '''\n",
    "    df_status = pd.read_sql_query(query, conn)\n",
    "    \n",
    "    if not df_status.empty:\n",
    "        col1, col2 = st.columns(2)\n",
    "        \n",
    "        with col1:\n",
    "            fig = px.pie(df_status, values='count', names='status',\n",
    "                         title='Records by Status')  # Renamed\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "        \n",
    "        with col2:\n",
    "            fig = px.pie(df_status, values='total_amount', names='status',\n",
    "                         title='Arrears Amount by Status')\n",
    "            st.plotly_chart(fig, use_container_width=True)\n",
    "    \n",
    "    # Penalty vs Interest Analysis\n",
    "    query = '''\n",
    "        SELECT \n",
    "            obligation_name,\n",
    "            SUM(penalty) as total_penalty,\n",
    "            SUM(interest) as total_interest\n",
    "        FROM tax_records\n",
    "        GROUP BY obligation_name\n",
    "        HAVING total_penalty > 0 OR total_interest > 0\n",
    "        ORDER BY (total_penalty + total_interest) DESC\n",
    "        LIMIT 10\n",
    "    '''\n",
    "    df_penalty_interest = pd.read_sql_query(query, conn)\n",
    "    \n",
    "    if not df_penalty_interest.empty:\n",
    "        st.subheader(\"Top 10 Obligations with Penalties and Interest\")\n",
    "        fig = px.bar(df_penalty_interest, x='obligation_name', \n",
    "                     y=['total_penalty', 'total_interest'],\n",
    "                     title='Penalty vs Interest by Obligation Type',\n",
    "                     barmode='group')\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "    \n",
    "    conn.close()\n",
    "\n",
    "\n",
    "def import_data_page(db_manager):\n",
    "    \"\"\"Data import page\"\"\"\n",
    "    st.title(\"📤 Import Data\")\n",
    "    \n",
    "    st.info(\"Upload a CSV file with tax data to import into the system\")\n",
    "    \n",
    "    uploaded_file = st.file_uploader(\"Choose a CSV file\", type=['csv'])\n",
    "    \n",
    "    if uploaded_file is not None:\n",
    "        # Show preview of uploaded data\n",
    "        try:\n",
    "            df_preview = pd.read_csv(uploaded_file)\n",
    "            st.subheader(\"Data Preview\")\n",
    "            st.dataframe(df_preview.head(10), use_container_width=True)\n",
    "            \n",
    "            # Reset file pointer\n",
    "            uploaded_file.seek(0)\n",
    "            \n",
    "            if st.button(\"Start Import\", type=\"primary\"):\n",
    "                # Save uploaded file temporarily\n",
    "                with open(\"temp_upload.csv\", \"wb\") as f:\n",
    "                    f.write(uploaded_file.getbuffer())\n",
    "                \n",
    "                with st.spinner(\"Importing data...\"):\n",
    "                    importer = DataImporter()\n",
    "                    result = importer.import_from_csv(\"temp_upload.csv\", db_manager)\n",
    "                    \n",
    "                    if 'error' in result:\n",
    "                        st.error(f\"Error importing data: {result['error']}\")\n",
    "                    else:\n",
    "                        st.success(\"✅ Import completed successfully!\")\n",
    "                        col1, col2, col3 = st.columns(3)\n",
    "                        col1.metric(\"Taxpayers Added\", result['taxpayers_added'])\n",
    "                        col2.metric(\"Records Added\", result['records_added'])  # Renamed\n",
    "                        col3.metric(\"Errors\", result['errors'])\n",
    "        except Exception as e:\n",
    "            st.error(f\"Error reading file: {e}\")\n",
    "\n",
    "\n",
    "def main():\n",
    "    \"\"\"Main application entry point\"\"\"\n",
    "    st.set_page_config(\n",
    "        page_title=\"Tax Arrears Management System\",\n",
    "        page_icon=\"💰\",\n",
    "        layout=\"wide\",\n",
    "        initial_sidebar_state=\"expanded\"\n",
    "    )\n",
    "    \n",
    "    # Initialize database\n",
    "    create_database()\n",
    "    \n",
    "    # Initialize session state\n",
    "    init_session_state()\n",
    "    \n",
    "    # Initialize database manager\n",
    "    db_manager = DatabaseManager()\n",
    "    \n",
    "    # Check authentication\n",
    "    if not st.session_state.authenticated:\n",
    "        login_page()\n",
    "        return\n",
    "    \n",
    "    # Sidebar navigation\n",
    "    with st.sidebar:\n",
    "        st.image(\"https://img.icons8.com/color/96/000000/tax.png\", width=80)\n",
    "        st.title(f\"Welcome, {st.session_state.username}\")\n",
    "        st.markdown(f\"**Role:** {st.session_state.role}\")\n",
    "        st.markdown(\"---\")\n",
    "        \n",
    "        # Navigation menu\n",
    "        menu_options = {\n",
    "            \"🏠 Dashboard\": dashboard_page,\n",
    "            \"👥 Taxpayers\": taxpayers_page,\n",
    "            \"📋 Tax Records\": records_page,  # Renamed\n",
    "            \"📈 Analytics\": analytics_page,\n",
    "        }\n",
    "        \n",
    "        # Add admin-only pages\n",
    "        if st.session_state.role == \"ADMIN\":\n",
    "            menu_options[\"📤 Import Data\"] = import_data_page\n",
    "        \n",
    "        selection = st.radio(\"Navigation\", list(menu_options.keys()))\n",
    "        \n",
    "        st.markdown(\"---\")\n",
    "        if st.button(\"🚪 Logout\", use_container_width=True):\n",
    "            st.session_state.authenticated = False\n",
    "            st.session_state.username = None\n",
    "            st.session_state.role = None\n",
    "            st.rerun()\n",
    "    \n",
    "    # Display selected page\n",
    "    menu_options[selection](db_manager)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env (3.13.2)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
